### ISSUE TITLE
Versioning issues

### ISSUE THREAD

**Issue by govereem** [wagento/zendesk#1]
The current git tag versioning is not semantic https://semver.org/
This causes packagist to fail https://packagist.org/packages/wagento/zendesk
Skipped tag m21v1.0.0, invalid tag name
Skipped tag m20v1.0.0, invalid tag name

Also the magento marketplace displays version 100.... not the 1.0.0 version
Maybe using tag v100.0.0 for m20v1.0.0 and v101.0.0 for m21v1.0.0

**Comment by wagento** [comment]
Hi @govereem, we are aware of the issue you've reported, from the beginning we wanted to have all module version available through composer but we got the tag problems, at that point our decision was to keep composer for the latest magento version, and support 2.1, 2.0 on github as a seperate release.

We are going to review your suggestion and probably we will apply it for next release (in module.xml 1.0.1).

**Comment by JDavidVR** [comment]
Hi @govereem your suggestion will be added to master branch, thanks for your help.
