### ISSUE TITLE
Authorization Issue when admin has a custom url.

### ISSUE THREAD

**Issue by JDavidVR** [wagento/zendesk#10]
Steps te reproduce:

Front URL: mystore.com
Typical Backend Url: mystore.com/admin
Custom Backend Url: customadmin.mystore.com/

So when click on authorize button, the back_url sent to Zendesk is using custom admin url, when it must be using the frontend URL

**Comment by lewis-chilton** [comment]
Please can we get an update on this?

We have just deployed to production and encountered the same issue.
Regardless of the Redirect URLs added in the oAuth config, this always returns a bad request, even if you amend the request url to include the website subdomain.

please advise asap.

**Comment by nmklong** [comment]
Having the same issue with this, any updates?

**Comment by JDavidVR** [comment]
@lewis-chilton , @nmklong 

Please install the latest module version:
https://github.com/wagento/zendesk/releases/tag/v220.0.2
