### ISSUE TITLE
Clearing cache on every init of the helper

### ISSUE THREAD

**Issue by JeroenBoersma** [wagento/zendesk#12]
https://github.com/wagento/zendesk/blob/6b8420a3ed493be826f3ba49bcee5aef49368ff5/Helper/Data.php#L60

Whenever this helper is used this clears the Magento config cache.
So, every page call will clear cache making Magento way slower than needed.

This should only happen if the config is actually updated.

Expected behavior: Don't clean cache on every __construct, only on save.

**Comment by JDavidVR** [comment]
Hi @JeroenBoersma ,

100% agree were are going to apply a fix for this issue in next release

**Comment by JDavidVR** [comment]
@JeroenBoersma 

Please install the latest module version:
https://github.com/wagento/zendesk/releases/tag/v220.0.2

**Comment by JeroenBoersma** [comment]
thanks!
