### ISSUE TITLE
Admin > Create Ticket Form: Two empty options displayed for TYPE and PRIORITY

### ISSUE THREAD

**Issue by admaduranga** [wagento/zendesk#13]
Steps to reproduce:

1. Go to Admin > Zendesk > Tickets > Create Ticket 
2. Look at the Type and Priority drop downs. There are two empty options rendered.

Two empty options are rendered as below.
`<option value="">-</option>
<option data-title="-" value="">-</option>`

![image](https://user-images.githubusercontent.com/13400841/44444692-473e1400-a608-11e8-867b-9c62bdbb8c39.png)

Please remove one, or both.

**Comment by JDavidVR** [comment]
@admaduranga 

I can't replicate the issue, what version of magento are you using?

**Comment by simonmaass** [comment]
i cant replicate either... magento 2.2.6... and version 220.0.2

**Comment by JDavidVR** [comment]
I am closing this becuase we can't replicate the issue
