### ISSUE TITLE
Select Order Grid : Redirects to Dashboard upon Sorting, Filtering, Pagination

### ISSUE THREAD

**Issue by admaduranga** [wagento/zendesk#14]
Steps to reproduce:

1. Admin > Zendesk >  Tickets > Create > Select Order 
2. From the popup try to sort the grid, or to filter it, or go to next page
3. You are redirected to the dashboard.

**Issue:**
\Wagento\Zendesk\Block\Adminhtml\Page\Widget\Order\Chooser::getGridUrl()
```php
return $this->getUrl('zendesk/page_widget/chooser', ['_current' => true]);
```
SHOULD BE LIKE THIS
```php
return $this->getUrl('zendesk/widget_order/chooser', ['_current' => true]);
```

``

**Comment by JDavidVR** [comment]
@admaduranga 
Thank you for your recommendation, we are going to apply the change and will improve the UI.

**Comment by JDavidVR** [comment]
@admaduranga 

Please install the latest module version:
https://github.com/wagento/zendesk/releases/tag/v220.0.2
