### ISSUE TITLE
Duplicate Tickets created on Zendesk/Magento

### ISSUE THREAD

**Issue by admaduranga** [wagento/zendesk#16]
Magento version: "magento/product-enterprise-edition": "2.1.10"

**Steps**

1. Admin > Zendesk > Create Ticket > Create
2. It takes a while and two tickets created on Magento
3. Two tickets created on Zendesk

**Trace:**
**./vendor/wagento/zendesk/view/adminhtml/ui_component/zendesk_ticket_form.xml:34**

```xml
<argument name="data" xsi:type="array">
        <item name="config" xsi:type="array">
            <item name="submit_url" xsi:type="url" path="zendesk/ticket/create"/>
            <item name="validate_url" xsi:type="url" path="zendesk/ticket/create"/>
        </item>
    </argument>
```

**validate_url** is also set to same **zendesk/ticket/create** action. When UIComponent tries to validate itself, It creates a ticket and then real **submit_url** is invoked and another ticket is created.

Can we change the **validate_url** please? 
Thanks

**Comment by JDavidVR** [comment]
@admaduranga 
Thanks for the update we are going to check this issue.

**Comment by JDavidVR** [comment]
Hi @admaduranga 

We are ending support this repo, a new version will available on marketplace: https://marketplace.magento.com/wagento-zendesk.html that will be compatible with m2.3.x version and will have some additional features.

Regards!
