### ISSUE TITLE
Ticket created from backend is not attaching order number

### ISSUE THREAD

**Issue by nmklong** [wagento/zendesk#18]
In the form in Magento 2's backend, there is a field called order number, but even after selecting the order, the ticket created in Zendesk doesn't have that order number attached.

When creating the ticket in order details on frontend, order number is saved correctly tho.

**Comment by JDavidVR** [comment]
Hi @nmklong , it can be a cache issue.

We figured out that the configuretion shuldn't be configurable, so by default it will be enabled in new realease.

**Comment by JDavidVR** [comment]
@donalddushi 
Please install the latest module version:
https://github.com/wagento/zendesk/releases/tag/v220.0.2
