### ISSUE TITLE
Order Details are not showing in ticket details

### ISSUE THREAD

**Issue by pramodtp** [wagento/zendesk#19]
Hi Team,

I have configured the extension as per https://github.com/wagento/zendesk/wiki/Magento-2-Connector#installation. But for some reason order details are not displaying on ticket details page.
Can someone share possible reason for this issue ?

Thanks!!!
<img width="642" alt="zendesk-master-issue" src="https://user-images.githubusercontent.com/42980302/47632806-9a38c800-db71-11e8-93b6-4e734d28313c.PNG">

**Comment by donalddushi** [comment]
Hi pramodtp,

which version of Wagento are you using?

**Comment by DePascual** [comment]
Hi!!
Same problem here. Is there any solution for that problem??
Thanks

**Comment by jhon-MT** [comment]
Hello @DePascual 

Can you confirm this problem is still existent in our latest version of Magento?

**Comment by davidhringur** [comment]
Hi, 
we are using the latest version of magento 2 and we have the same issue. I don't know if the connection between zendesk and magento is not working or if this is a bug. I cant seem to find any way to check if the connection works between the two.
Thanks

**Comment by JDavidVR** [comment]
Hi @pramodtp 

We are ending support this repo, a new version will available on marketplace: https://marketplace.magento.com/wagento-zendesk.html that will be compatible with m2.3.x version and will have some additional features.

Regards!
