### ISSUE TITLE
the customer can not add comments to his ticket

### ISSUE THREAD

**Issue by donalddushi** [wagento/zendesk#20]
Hi,

I have only one problem with Magento-Zendesk
the customer can not add comments to his ticket

I have these configurations:
- Magento version: Magento-CE-2.2.6_sample_data-2018-09-07-02-38-51
- Php version: 7 on Ubuntu 16.04
- Module Version: zendesk-220.0.1
- Cache status: All disabled

I would like to note that all the other functions work correctly

![wagento_zendesk-add-comment](https://user-images.githubusercontent.com/26249867/47657406-4c33bc80-db91-11e8-8ca3-f8ae0a850ef2.png)

**Comment by JDavidVR** [comment]
Hi!, @donalddushi ,

We figured out the problem we are going to push changes in a few hours

**Comment by JDavidVR** [comment]
@donalddushi 
Please install the latest module version:
https://github.com/wagento/zendesk/releases/tag/v220.0.2
