### ISSUE TITLE
Missing Order Number ID Field in Backend

### ISSUE THREAD

**Issue by simonmaass** [wagento/zendesk#22]
This is how it looks in you wiki:
![order_number_field_id_wiki](https://user-images.githubusercontent.com/32599710/48788525-4e4dee80-eceb-11e8-8767-632853798222.png)

In my magento 2 backend i can only see this:
![order_number_field_id_missing](https://user-images.githubusercontent.com/32599710/48788543-57d75680-eceb-11e8-9794-23ee6d4af210.png)

Using Magento 2.2.6 and module version 220.0.2

**Comment by simonmaass** [comment]
Ok if i hit save it created the Field in Zendesk and saves the field ID in the backend.... i guess works as designed.... just the admin backend looks different to the wiki

**Comment by JDavidVR** [comment]
Hi @simonmaass 

Thanks for the update, yes, we have changed that field, because it was required for many tickets creation, and when it was disabled, was causing some issues.

We are going to update Wiki and user guide to have the lastest changes.
