### ISSUE TITLE
Change Order Field Label in Zendesk

### ISSUE THREAD

**Issue by simonmaass** [wagento/zendesk#23]
If i change the Lable of the Ticket Field it creates a new Ticketfield in Zendesk...Should it not check for the ID of the field....

vendor\wagento\zendesk\Observer\AdminZendesk.php: 176

Line:
$orderFields = $this->ticketField->getList();
$userFieldKeys = array_column($orderFields, 'title', 'id');
$filterId = array_keys($userFieldKeys, self::ORDER_FIELD_LABEL);

**Comment by JDavidVR** [comment]
Hi @simonmaass ,

Thanks for the update, in this case we are filtering by label, becuase we want to make sure that it always exists, and if it doesn't exist we will create it.

But we can make an improvement to valider first the if FieldId stored in magento exists on Zendesk.

**Comment by JDavidVR** [comment]
Hi @simonmaass 

We are ending support this repo, a new version will available on marketplace: https://marketplace.magento.com/wagento-zendesk.html that will be compatible with m2.3.x version and will have some additional features.

Regards!
