### ISSUE TITLE
Limit for 100 Tickets

### ISSUE THREAD

**Issue by simonmaass** [wagento/zendesk#24]
![limit100](https://user-images.githubusercontent.com/32599710/48838410-87886c00-ed88-11e8-8dc4-9c1fb2279ea8.png)

it seems that somehow i can only see the first 100 tickets...

**Comment by simonmaass** [comment]
@JDavidVR any idea?

**Comment by JDavidVR** [comment]
Hi @simonmaass 

Thanks for submitting this issue,  looks like api has a limit: 
https://developer.zendesk.com/rest_api/docs/support/tickets#list-tickets

And Zendesk recommends to use:
https://developer.zendesk.com/rest_api/docs/support/introduction#pagination

We are going to review this scenario and find the best solution to handle it using magento's default grid.

**Comment by JDavidVR** [comment]
Hi @simonmaass 

We are ending support this repo, a new version will available on marketplace: https://marketplace.magento.com/wagento-zendesk.html that will be compatible with m2.3.x version and will have some additional features.

Regards!
