### ISSUE TITLE
the customer can not open the ticket created by a zendesk agent

### ISSUE THREAD

**Issue by donalddushi** [wagento/zendesk#25]
hi,

I verified that if an agent creates a ticket on behalf of a customer , the customer can not view this ticket 

thanks
![ticket](https://user-images.githubusercontent.com/26249867/48900089-b880a380-ee51-11e8-9866-8c95ce738484.PNG)

**Comment by jhon-MT** [comment]
Hello @donalddushi 

I apologize for this very late response. Is this still happening?

Can I confirm how is the agent creating the ticket? Is the ticket being created directly in the Zendesk Platform? 

Thanks for allowing us to improve the extension!

Jhon

**Comment by hiren-wagento** [comment]
The issue described by @donalddushi can only arise if any one of below condition occurs.
- ticket not exist in zendesk
- zendesk-User-Id  NOT EQUALS requester_id of a ticket
- zendesk-User-Id  NOT EQUALS submitter_id of a ticket

But unfortunately I could not reproduce this issue.
- I have tried to create ticket using M2 admin panel.
- I have tried to create ticket using frontend customer's account.

But for all the cases I can view the ticket.

**Comment by JDavidVR** [comment]
Hi @donalddushi 

We are ending support this repo, a new version will available on marketplace: https://marketplace.magento.com/wagento-zendesk.html that will be compatible with m2.3.x version and will have some additional features.

Regards!
