### ISSUE TITLE
compatibility m2.3 and php 7.2

### ISSUE THREAD

**Issue by simonmaass** [wagento/zendesk#26]
hello, does this run on magent 2.3 and php 7.2?

**Comment by simonmaass** [comment]
any news here on magento 2.3 support???

**Comment by DePascual** [comment]
Hi
I'm very interested too in a version compatible with the new release of Magento. 
Any news??
Thanks

**Comment by jhon-MT** [comment]
Hello @simonmaass and @DePascual 

Currently we are in the planning stage of a new version of the xtension to be fully compatible with Magento 2.3 and support PHP 7.2. However, we do not have date when this will get published in the Marketplace.
It should be happening within the next 2 months though.

Thanks!

**Comment by Swahjak** [comment]
@jhon-MT is this still part of your timeline?

**Comment by jhon-MT** [comment]
Hello @Swahjak we are in the final round of testing for publishing the upgraded version.
The current version however is already compatible with Magento 2.3

Thanks,

**Comment by TonyRutherford1** [comment]
@jhon-wagento Any update?

**Comment by TonyRutherford1** [comment]
@jhon-wagento Any update on release date?

**Comment by jhon-wagento** [comment]
Hello @TonyRutherford1 we have submitted the app for release in the marketplace. We are awaiting Magento to publish it only.

Thanks

**Comment by TonyRutherford1** [comment]
@jhon-wagento Amazing. Thank you for the update

**Comment by JDavidVR** [comment]
Hi @simonmaass 

We are ending support this repo, a new version will available on marketplace: https://marketplace.magento.com/wagento-zendesk.html that will be compatible with m2.3.x version and will have some additional features.

Regards!
