### ISSUE TITLE
Creating a Ticket in Front end  but it's not listing on Magento as ticket

### ISSUE THREAD

**Issue by tanolalano** [wagento/zendesk#27]
Hi, 
I've some problem with the app.
I'm on magento 2.2.6 with php 7.1.22. The issue persist both default luma theme and on my theme

When a user submit a ticket from order list of magento the ticket is created but Customer get an error (screen2). 
The ticket is created in zendesk support but it has as email address the Magento Store default one (screen3) not the customer's email.

The default page (Mydomain.com/customer/account/index/) of customer is messed. It shows only a text with costumer last order (screen1) 

![screen3](https://user-images.githubusercontent.com/4384863/50604712-247a1100-0ec0-11e9-9fb5-8c1babb96429.png)
![screen1](https://user-images.githubusercontent.com/4384863/50604713-247a1100-0ec0-11e9-82c2-68af8a8d80d7.png)
![screen2](https://user-images.githubusercontent.com/4384863/50604714-247a1100-0ec0-11e9-8dbe-17d52754ff27.png)

 
On Apache error log I found
`AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function setData() on boolean in /opt/bitnami/apps/magento/htdocs/vendor/wagento/zendesk/view/frontend/templates/order/recent.phtml:57\nStack trace:\n#0 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()\n#1 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/Template.php(270): Magento\\Framework\\View\\TemplateEngine\\Php->render(Object(Magento\\Sales\\Block\\Order\\Recent), '/opt/bitnami/ap...', Array)\n#2 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/Template.php(300): Magento\\Framework\\View\\Element\\Template->fetchView('/opt/bitnami/ap...')\n#3 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-sales/Block/Order/Recent.php(131): Magento\\Framework\\View\\Element\\Template->_toHtml()\n#4 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\\Sales\\Block\\Order\\Recent->_toHtml()\n#5 /opt/bitnami/apps/magento/htdocs/ve...\n', referer: https://arancebio.it/customer/account/login/
[Wed Jan 02 17:49:31.190492 2019] [proxy_fcgi:error] [pid 14374:tid 139912752359168] `

**Comment by JDavidVR** [comment]
Hi! @tanolalano  thanks for reporting this issue, we are going to take a look.

**Comment by hiren-wagento** [comment]
For the same magento(CE 2.2.6) & PHP version (7.1.22), I have tried a lot to reproduce this issue. But initially I can't reproduce it.

But when I manually deletes the Zendesk User Id for one of the customer, I could reproduce the issue (The ticket is created in zendesk support but it has as email address the Magento Store default one not the customer's email.).

**Solution:**
To solve this issue, magento admin needs to manually Synchronize Customers. See below screen.

![image](https://user-images.githubusercontent.com/23444023/52762714-bb4cf800-303e-11e9-80b7-019e13623bc6.png)

**Comment by JDavidVR** [comment]
Hi @tanolalano 

We are ending support this repo, a new version will available on marketplace: https://marketplace.magento.com/wagento-zendesk.html that will be compatible with m2.3.x version and will have some additional features.

Regards!
