### ISSUE TITLE
Cron Execution Enablement Logic Backwards Inadvertently Preventing Cron Sync

### ISSUE THREAD

**Issue by bap14** [wagento/zendesk#29]
https://github.com/wagento/zendesk/blob/9c7401fee35dc4ecd29944c0930434a21d44665d/Cron/Sync.php#L61

The above logic shows that if you select "enabled" in the Magento configuration for cron sync, it will in fact not execute. Instead it should be:

```php
        if(!$isEnabled) return;
```

**Comment by JDavidVR** [comment]
Hi @bap14 , thank you for your feedback and help.

We are ending support this repo, a new version will available on marketplace: https://marketplace.magento.com/wagento-zendesk.html that will be compatible with m2.3.x version and will have some additional features.

Regards!
