### ISSUE TITLE
php 7.3 compatibility

### ISSUE THREAD

**Issue by jordanvector** [wagento/zendesk#32]
The latest version of magento 2.3.3 its compatibile with 7.3 but it looks like the zendesk module has a max php version of 7.2.  Is there any reason it would not be compatible with 7.3?

**Comment by jhon-wagento** [comment]
Hello Jordan,

The extension is not yet checked for Magento 2.3.3.

In addition, this free version is no longer going to be supported over here any more. Should you need assistance, please email to support@wagento.com 

Thank you,

Jhon

**Comment by JDavidVR** [comment]
Hi @jordanvector 

We are ending support this repo, a new version will available on marketplace: https://marketplace.magento.com/wagento-zendesk.html that will be compatible with m2.3.x version and will have some additional features.

Regards!
