### ISSUE TITLE
Database query error when retrieving customer orders

### ISSUE THREAD

**Issue by leoquijano** [wagento/zendesk#4]
Hi,

I'm having a DB query error when trying to retrieve orders for a guest customer. The affected code is in ```Model/CustomerOrderRepository.php```, for the Magento v2.2.2 version of the ```Wagento_Zendesk``` module:

```
if (!$customerData) {
    $select = $orderConnection->select()->from(
        $orderTable,
        [
            'email' => 'customer_email',
            'firstname' => 'customer_firstname',
            'lastname' => 'customer_lastname',
            'group_id' => 'customer_group_id'
        ]
    )->where(
        'customer_email = ?', $email
    )->order(['id DESC'])
        ->limit(1);
    $customerData = $orderConnection->fetchRow($select);
}
```

If the query is ordered by ```id```, MySQL will throw the following error:

```
Column not found: 1054 Unknown column 'id' in 'order clause', query was: SELECT `sales_order`.`customer_email` AS `email`, `sales_order`.`customer_firstname` AS `firstname`, `sales_order`.`customer_lastname` AS `lastname`, `sales_order`.`customer_group_id` AS `group_id` FROM `sales_order` WHERE (customer_email = '<EMAIL>') ORDER BY `id` DESC
```

This is fixed by replacing the ```id``` in the ```order``` method, by ```entity_id```.

This issue might be affecting other areas of this module. I'm reporting one of them in case you want to address it in your official version.

**Comment by wagento** [comment]
Hi @leoquijano we are going to include this fix in the next release, thanks for your contribution.

**Comment by JDavidVR** [comment]
@leoquijano your changes suggested are in branch master, thanks for the update.
