### ISSUE TITLE
Invalid Authorization Request  bad_request

### ISSUE THREAD

**Issue by cyberkiller6** [wagento/zendesk#5]
Using release, m2.1.x v1.0.0 on Magento 2.1.2

I get the following error when trying to authorize the extension, 

Invalid Authorization Request

bad_request

Anyone else encounter this?

**Comment by BrianHeeseIs** [comment]
I have same issue, when configuring in magento 2 and clicking button "Authorize" i get a popup with a message saying "bad_request"

**Comment by JDavidVR** [comment]
Hi! @BrianHeeseIs and @cyberkiller6 we added many changes to master branch, it solves 3 main issues:
- Authorize click button and a cache issue that occurs
- Customer sync
- Better Installation algortihm

We are going to apply same fixes for branchs 2.0 and 2.1, you can download the commit as a patch in case you want o apply changes ASAP,  this is the commit: 6b8420a3ed493be826f3ba49bcee5aef49368ff5

In case you are testing in a dev or stage enviroment, make sure that you have valid ssl installed, that is more a policy from zendesk that only secure sites can use the api, if you are in local enviroment your domain needs to be some thing like http://localhost/mymagento, localhost and 127.0.0.1 are the only valid names allowed by zendesk to skip the https validation.

**Comment by cyberkiller6** [comment]
Thank you, what's the eta on the patch for 2.1?

**Comment by JDavidVR** [comment]
@cyberkiller6 we have released all module changes for all magento version, feel free to download it from: https://github.com/wagento/zendesk/releases, in the next day we are going to submit the latest version to magento's marketplace (only for m2.2)

**Comment by nmklong** [comment]
I'm getting this error on the latest release, testing from localhost, is that possibly a reason?
