### ISSUE TITLE
v1.0.1 for M2.1.x (composer v210.0.1)

### ISSUE THREAD

**Issue by cyberkiller6** [wagento/zendesk#6]
PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Framework\App\Config::clean() in /home/magento/public_html/app/code/Wagento/Zendesk/Helper/Data.php:60
Stack trace:
#0 /home/magento/public_html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(93): Wagento\Zendesk\Helper\Data->__construct(Object(Magento\Framework\App\Helper\Context), Object(Magento\Framework\Encryption\Encryptor), Object(Magento\Framework\App\Config\Storage\Writer))
#1 /home/magento/public_html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Wagento\\Zendesk...', Array)
#2 /home/magento/public_html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Wagento\\Zendesk...')
#3 /home/magento/public_html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Wagento\\ in /home/magento/public_html/app/code/Wagento/Zendesk/Helper/Data.php on line 60

Magento ver. 2.1.2

**Comment by JDavidVR** [comment]
Hi! @cyberkiller6 thanks for opening this issue we are going to review it.

**Comment by cyberkiller6** [comment]
Any update on this? Were you able to reproduce the errors on your end?

**Comment by JDavidVR** [comment]
Hi @cyberkiller6  yes we were able to replicate te issue, we are looking for a good solution that will work for all 2.1.x and 2.0.x version, we hope to have updates for this week.

**Comment by JDavidVR** [comment]
Hi @cyberkiller6 

We are ending support this repo, a new version will available on marketplace: https://marketplace.magento.com/wagento-zendesk.html that will be compatible with m2.3.x version and will have some additional features.

Regards!
