### ISSUE TITLE
unable to filter order grid 

### ISSUE THREAD

**Issue by MaxyBlack** [wagento/zendesk#7]
https://github.com/wagento/zendesk/blob/dac1f80be17f1653a7e47e0afcc48fe3ae65af8b/Block/Adminhtml/Page/Widget/Customer/Chooser.php#L201
https://github.com/wagento/zendesk/blob/dac1f80be17f1653a7e47e0afcc48fe3ae65af8b/Block/Adminhtml/Page/Widget/Order/Chooser.php#L188
should be 
`return $this->getUrl('zendesk/widget_order/chooser', ['_current' => true]);`

**Comment by MaxyBlack** [comment]
@wagento are you guys interested in fixing this?

**Comment by JDavidVR** [comment]
Hi @MaxyBlack !
Thanks for sharing the improvement we are going to make changes and test, the we are going to push your changes in next release.

**Comment by MaxyBlack** [comment]
@JDavidVR thank you for your response :)

**Comment by MaxyBlack** [comment]
@wagento hi, any progress with this?

**Comment by JDavidVR** [comment]
@MaxyBlack 
Please install the latest module version:
https://github.com/wagento/zendesk/releases/tag/v220.0.2

**Comment by MaxyBlack** [comment]
@JDavidVR it's too late. I don't work anymore in my previous company and before I left your module was replaced with my port.
