### ISSUE TITLE
Authorization issue on ver. 2.2.2

### ISSUE THREAD

**Issue by franconicolasocchi** [wagento/zendesk#8]
I'm getting "Secret is invalid" when try to authorize. I commented out the return secret value from the helper and just return the crud value but now shows the next error.

<img width="786" alt="captura de pantalla 2018-06-12 a las 11 43 17" src="https://user-images.githubusercontent.com/10506275/41297604-e0a02fee-6e35-11e8-9da1-2d43084d1177.png">

**Comment by SamB-GB** [comment]
Usually that means the redirections on your oAuth app in Zendesk isn't set.

**Comment by JDavidVR** [comment]
Hi @franconicolasocchi 
Please disable Magento's Cache, do a `bin/magento cache:flush;` and try to authorise  again, once you make sure that token is correct, you can enable Magento's cache again.

**Comment by franconicolasocchi** [comment]
Thanks @SamB-GB and @JDavidVR. The callbacks urls are set ok, and even disabling the cache is the same.

**Comment by simonmaass** [comment]
I have the same issue... What are the requirements for the callbacks?

**Comment by simonmaass** [comment]
Using Magento 2.2.6 and Version 220.0.2

**Comment by simonmaass** [comment]
wrong call back urls... now it works!

**Comment by JDavidVR** [comment]
@simonmaass 

Yes, it's recommended to double check url validation.
